### ISSUE TITLE
NameError: name 'OpenPose' is not defined

### ISSUE THREAD

**Issue by chamecall** [nishagandhi/OpenPose_PythonOpenCV#1]
I can't find module class OpenPose in module openpose.
My trace:
```
Traceback (most recent call last):
  File "test.py", line 74, in <module>
    main()
  File "test.py", line 37, in main
    openpose = OpenPose(params)
NameError: name 'OpenPose' is not defined
```
It seemed that there's no class with such name like OpenPose in here.

**Comment by mathpopo** [comment]
ihave same issue

**Comment by natcan-cvip** [comment]
same error too
anyone has solved?

**Comment by fpretto** [comment]
Hi, I'm having the same issue. Has someone figured out how to solve it?

**Comment by murugeshmanthiramoorthi** [comment]
I am also facing the same issue. Any solutions?

**Comment by chamecall** [comment]
Sorry guys I don't remember what exactly I changed but eventually I had used OpenPose in [such manner](https://github.com/chamecall/PullUpCounter/blob/030be5855b5c5669be97610d2b8ee7a14789f624/Preprocessor.py#L48).

**Comment by johnsk95** [comment]
I think she used an old version of openpose. I don't see the 'Openpose' constructor in the latest openpose python examples.
